version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Create Initialisatiion script
          command: |
            sudo apt-get update
            sudo apt install git-all
            git clone https://github.com/ANSHUKPANDEY/Anshu1.git
            sudo pip install Flask
            cd appnew
      - run:  
          name: Build Docker Image
          command: |
           docker build -t appnew -f appnew/Dockerfile .
      - run:     
          name: Create docker container
          command: |
           docker run -d -p 56733:80 --name=appnew appnew


