- name: update apt package cache
  apt: update_cache=yes

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - software-properties-common
    - build-essential
    - git
    - vim

- name: Install python
  raw: apt install -y python-minimal


- name: Install pip
  raw: apt install -y python-pip


- name: Install pip3
  raw: apt install -y python3-pip


